"""
Fraud Detection Flow - Python Export Approach for Langflow

This module simulates what Langflow would export when using the "Python Function" option.
It provides a self-contained fraud detection flow that can be used as a tool in the agent service.

In a real scenario, this code would be generated by Langflow's export feature.
"""

from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime
import re


@dataclass
class FraudDetectionInput:
    """Input schema for fraud detection flow."""
    claim_id: str
    patient_name: str
    total_amount: float
    diagnosis_codes: List[str]
    provider_name: str
    submission_date: str
    notes: Optional[str] = None
    previous_claims_count: int = 0
    previous_claims_amount: float = 0.0


@dataclass
class FraudDetectionOutput:
    """Output schema for fraud detection flow."""
    risk_score: float  # 0.0 to 1.0
    risk_level: str  # "low", "medium", "high", "critical"
    flags: List[Dict[str, Any]]
    recommendation: str
    details: Dict[str, Any]
    processed_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())


class FraudDetectionFlow:
    """
    Fraud Detection Flow - Exported from Langflow

    This class mimics the structure of code exported from Langflow when using
    the "Python Function" export option. It encapsulates the complete flow logic.

    Flow Components (as configured in Langflow):
    1. Input Parser - Validates and structures input data
    2. Amount Checker - Flags high-value claims
    3. Velocity Checker - Detects unusual submission patterns
    4. Pattern Matcher - Identifies suspicious keywords/phrases
    5. Risk Calculator - Aggregates risk factors into a score
    6. Output Formatter - Structures the final response
    """

    # Configuration constants (would come from Langflow component settings)
    HIGH_AMOUNT_THRESHOLD = 10_000_000  # VND
    CRITICAL_AMOUNT_THRESHOLD = 50_000_000  # VND
    VELOCITY_CLAIMS_THRESHOLD = 3  # claims in period
    VELOCITY_AMOUNT_THRESHOLD = 30_000_000  # VND in period

    # Suspicious keywords for pattern matching
    SUSPICIOUS_KEYWORDS = [
        "urgent", "emergency", "immediate", "asap", "rush",
        "confidential", "private", "do not verify", "bypass",
        "override", "exception", "special handling", "off the record"
    ]

    # High-risk diagnosis patterns
    HIGH_RISK_DIAGNOSES = [
        r"V.*",  # External causes of morbidity (potential fraud indicators)
        r"Z71\..*",  # Person encountering health services for other counseling
    ]

    def __init__(self):
        """Initialize the fraud detection flow."""
        self.flags: List[Dict[str, Any]] = []
        self.risk_factors: Dict[str, float] = {}

    async def run(self, claim_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Execute the fraud detection flow.

        This is the main entry point that Langflow would generate.
        It orchestrates all the flow components.

        Args:
            claim_data: Dictionary containing claim information

        Returns:
            Dictionary with fraud detection results
        """
        try:
            # Step 1: Parse Input
            input_data = self._parse_input(claim_data)

            # Step 2: Run checks
            await self._check_amount(input_data)
            await self._check_velocity(input_data)
            await self._check_patterns(input_data)
            await self._check_diagnosis_codes(input_data)

            # Step 3: Calculate risk score
            risk_score = self._calculate_risk_score()
            risk_level = self._determine_risk_level(risk_score)

            # Step 4: Generate recommendation
            recommendation = self._generate_recommendation(risk_score, risk_level)

            # Step 5: Format output
            output = FraudDetectionOutput(
                risk_score=risk_score,
                risk_level=risk_level,
                flags=self.flags,
                recommendation=recommendation,
                details={
                    "claim_id": input_data.claim_id,
                    "patient_name": input_data.patient_name,
                    "amount_checked": input_data.total_amount,
                    "risk_factors": self.risk_factors,
                    "total_flags": len(self.flags),
                }
            )

            return self._output_to_dict(output)

        except Exception as e:
            return self._handle_error(e)

    def _parse_input(self, claim_data: Dict[str, Any]) -> FraudDetectionInput:
        """Parse and validate input data."""
        return FraudDetectionInput(
            claim_id=claim_data.get("claim_id", "UNKNOWN"),
            patient_name=claim_data.get("patient_name", ""),
            total_amount=float(claim_data.get("total_amount", 0)),
            diagnosis_codes=claim_data.get("diagnosis_codes", []),
            provider_name=claim_data.get("provider_name", ""),
            submission_date=claim_data.get("submission_date", datetime.utcnow().isoformat()),
            notes=claim_data.get("notes"),
            previous_claims_count=int(claim_data.get("previous_claims_count", 0)),
            previous_claims_amount=float(claim_data.get("previous_claims_amount", 0)),
        )

    async def _check_amount(self, data: FraudDetectionInput) -> None:
        """Check if claim amount exceeds thresholds."""
        amount = data.total_amount

        if amount >= self.CRITICAL_AMOUNT_THRESHOLD:
            self.flags.append({
                "type": "critical_amount",
                "severity": "high",
                "message": f"Claim amount ({amount:,.0f} VND) exceeds critical threshold",
                "threshold": self.CRITICAL_AMOUNT_THRESHOLD,
                "actual": amount,
            })
            self.risk_factors["critical_amount"] = 0.4
        elif amount >= self.HIGH_AMOUNT_THRESHOLD:
            self.flags.append({
                "type": "high_amount",
                "severity": "medium",
                "message": f"Claim amount ({amount:,.0f} VND) exceeds normal threshold",
                "threshold": self.HIGH_AMOUNT_THRESHOLD,
                "actual": amount,
            })
            self.risk_factors["high_amount"] = 0.2

    async def _check_velocity(self, data: FraudDetectionInput) -> None:
        """Check for unusual velocity patterns."""
        # Check number of previous claims
        if data.previous_claims_count >= self.VELOCITY_CLAIMS_THRESHOLD:
            self.flags.append({
                "type": "high_velocity_count",
                "severity": "medium",
                "message": f"Patient has {data.previous_claims_count} recent claims",
                "threshold": self.VELOCITY_CLAIMS_THRESHOLD,
                "actual": data.previous_claims_count,
            })
            self.risk_factors["velocity_count"] = 0.15

        # Check total amount of previous claims
        if data.previous_claims_amount >= self.VELOCITY_AMOUNT_THRESHOLD:
            self.flags.append({
                "type": "high_velocity_amount",
                "severity": "medium",
                "message": f"Patient has {data.previous_claims_amount:,.0f} VND in recent claims",
                "threshold": self.VELOCITY_AMOUNT_THRESHOLD,
                "actual": data.previous_claims_amount,
            })
            self.risk_factors["velocity_amount"] = 0.15

    async def _check_patterns(self, data: FraudDetectionInput) -> None:
        """Check for suspicious patterns in notes and fields."""
        text_to_check = " ".join(filter(None, [
            data.notes,
            data.provider_name,
        ])).lower()

        found_keywords = []
        for keyword in self.SUSPICIOUS_KEYWORDS:
            if keyword in text_to_check:
                found_keywords.append(keyword)

        if found_keywords:
            self.flags.append({
                "type": "suspicious_keywords",
                "severity": "high" if len(found_keywords) > 2 else "medium",
                "message": f"Suspicious keywords detected: {', '.join(found_keywords)}",
                "keywords_found": found_keywords,
                "count": len(found_keywords),
            })
            self.risk_factors["suspicious_keywords"] = min(0.1 * len(found_keywords), 0.3)

        # Check for suspicious provider patterns
        if data.provider_name:
            # Check for generic or suspicious provider names
            generic_patterns = ["unknown", "private", "individual", "self"]
            if any(pattern in data.provider_name.lower() for pattern in generic_patterns):
                self.flags.append({
                    "type": "suspicious_provider",
                    "severity": "medium",
                    "message": f"Provider name may be suspicious: {data.provider_name}",
                    "provider": data.provider_name,
                })
                self.risk_factors["suspicious_provider"] = 0.1

    async def _check_diagnosis_codes(self, data: FraudDetectionInput) -> None:
        """Check diagnosis codes for high-risk patterns."""
        high_risk_codes = []

        for code in data.diagnosis_codes:
            for pattern in self.HIGH_RISK_DIAGNOSES:
                if re.match(pattern, code, re.IGNORECASE):
                    high_risk_codes.append(code)
                    break

        if high_risk_codes:
            self.flags.append({
                "type": "high_risk_diagnosis",
                "severity": "medium",
                "message": f"High-risk diagnosis codes detected: {', '.join(high_risk_codes)}",
                "codes": high_risk_codes,
            })
            self.risk_factors["high_risk_diagnosis"] = 0.15

    def _calculate_risk_score(self) -> float:
        """Calculate overall risk score from risk factors."""
        base_score = sum(self.risk_factors.values())
        # Cap at 1.0
        return min(round(base_score, 2), 1.0)

    def _determine_risk_level(self, score: float) -> str:
        """Determine risk level from score."""
        if score >= 0.7:
            return "critical"
        elif score >= 0.5:
            return "high"
        elif score >= 0.3:
            return "medium"
        else:
            return "low"

    def _generate_recommendation(self, score: float, level: str) -> str:
        """Generate recommendation based on risk assessment."""
        recommendations = {
            "critical": "IMMEDIATE MANUAL REVIEW REQUIRED. Multiple high-risk indicators detected. Consider fraud investigation.",
            "high": "Manual review recommended. Verify claim details and supporting documentation before approval.",
            "medium": "Standard review with additional verification of flagged items.",
            "low": "Standard automated processing. No additional verification required.",
        }

        recommendation = recommendations.get(level, recommendations["low"])

        # Add specific actions based on flags
        actions = []
        for flag in self.flags:
            if flag["type"] == "critical_amount":
                actions.append("Verify high-value claim with senior adjuster")
            elif flag["type"] == "suspicious_keywords":
                actions.append("Review claim notes for policy compliance")
            elif flag["type"] == "high_velocity_count":
                actions.append("Check for duplicate or related claims")

        if actions:
            recommendation += f" Specific actions: {'; '.join(actions)}."

        return recommendation

    def _output_to_dict(self, output: FraudDetectionOutput) -> Dict[str, Any]:
        """Convert output dataclass to dictionary."""
        return {
            "risk_score": output.risk_score,
            "risk_level": output.risk_level,
            "flags": output.flags,
            "recommendation": output.recommendation,
            "details": output.details,
            "processed_at": output.processed_at,
            "status": "success",
        }

    def _handle_error(self, error: Exception) -> Dict[str, Any]:
        """Handle errors gracefully."""
        return {
            "risk_score": 0.0,
            "risk_level": "unknown",
            "flags": [{
                "type": "processing_error",
                "severity": "high",
                "message": f"Error processing fraud detection: {str(error)}",
            }],
            "recommendation": "Manual review required due to processing error.",
            "details": {"error": str(error)},
            "processed_at": datetime.utcnow().isoformat(),
            "status": "error",
        }


# Convenience function for direct usage
async def run_fraud_detection(claim_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convenience function to run fraud detection without instantiating the class.

    This function signature matches what Langflow typically exports for simple usage.
    """
    flow = FraudDetectionFlow()
    return await flow.run(claim_data)
