"""State definition for ReAct agent graph."""
from typing import TypedDict, Annotated, List, Dict, Any, Optional
import operator


class AgentState(TypedDict):
    """State for the ReAct agent.

    This state is passed between nodes in the LangGraph.
    Each field represents a piece of the agent's working memory.
    """

    # === Input Data ===
    claim_id: str
    extracted_data: Dict[str, Any]
    policy_number: str
    submission_date: Optional[str]

    # === ReAct Loop ===
    # Observations gathered from extraction and context
    observations: Annotated[List[str], operator.add]

    # Reasoning steps generated by LLM
    thoughts: Annotated[List[str], operator.add]

    # Actions taken by the agent
    actions: Annotated[List[Dict[str, Any]], operator.add]

    # Reflections on action results
    reflections: Annotated[List[str], operator.add]

    # === Context ===
    # Retrieved policy/medical knowledge
    retrieved_context: List[Dict[str, Any]]

    # Results from tool executions
    tool_results: Annotated[List[Dict[str, Any]], operator.add]

    # === Output ===
    decision: Optional[str]  # APPROVE, REJECT, PENDING
    confidence_score: float
    amount_recommended: float
    reasoning: str
    evidence: List[Dict[str, Any]]
    risks: List[str]

    # === Control ===
    iteration_count: int
    max_iterations: int
    should_continue: bool
    error: Optional[str]


def create_initial_state(
    claim_id: str,
    extracted_data: Dict[str, Any],
    policy_number: str,
    submission_date: Optional[str] = None,
    max_iterations: int = 10
) -> AgentState:
    """Create initial state for a new claim processing."""
    return {
        # Input
        "claim_id": claim_id,
        "extracted_data": extracted_data,
        "policy_number": policy_number,
        "submission_date": submission_date,

        # ReAct loop (empty initially)
        "observations": [],
        "thoughts": [],
        "actions": [],
        "reflections": [],

        # Context (empty initially)
        "retrieved_context": [],
        "tool_results": [],

        # Output (empty initially)
        "decision": None,
        "confidence_score": 0.0,
        "amount_recommended": 0.0,
        "reasoning": "",
        "evidence": [],
        "risks": [],

        # Control
        "iteration_count": 0,
        "max_iterations": max_iterations,
        "should_continue": True,
        "error": None
    }
