services:
  mongodb:
    image: mongodb/mongodb-atlas-local:latest
    container_name: mongodb_thesis
    hostname: mongodb
    env_file:
      - ../../.env
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-admin123}
      - MONGOT_LOG_FILE=/dev/stderr
      - RUNNER_LOG_FILE=/dev/stderr
    ports:
      - "27017:27017"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d:ro
      - db:/data/db
      - configdb:/data/configdb
      - mongot:/data/mongot

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-thesis
    env_file:
      - ../../.env
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-admin123}@mongodb:27017
      - ME_CONFIG_BASICAUTH=false
    depends_on:
      - mongodb

volumes:
  db:
  configdb:
  mongot: